version: "3.4"
services:
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=desafio-fabricio
      - POSTGRES_PASSWORD=postgres123456789
      - POSTGRES_DB=desafio-fabricio
    ports:
      - "5000:5000"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "murilo.rs.campos@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
